name: 'publish'
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
jobs:
  version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - uses: cho0o0/calver-release-action@release
        id: calver
        with:
          dry_run: false
          api_token: ${{secrets.GITHUB_TOKEN}}
