name: 'test'
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm install
          npm run all
      - uses: ./
        id: calver
        with:
          api_token: ${{secrets.GITHUB_TOKEN}}
          dry_run: true
      - run: echo ${{ steps.calver.outputs.version }}
      - uses: ./
        id: calver_with_parameters
        with:
          api_token: ${{secrets.GITHUB_TOKEN}}
          dry_run: true
          generate_release_notes: false
          timezone: Asia/Shanghai
          target_commitish: ${{ github.sha }}
      - run: echo ${{ steps.calver_with_parameters.outputs.version }}


